sudo: false

language: python

python:
- '2.7'
- '3.4'
- '3.5'

cache:
  directories:
  - $HOME/.cache/pip

install:
- pip install -r requirements.txt
- python setup.py develop

script: py.test

notifications:
  irc:
    channels:
    - irc.freenode.net##ban
    on_success: change
    on_failure: always
  email: false
